[package]
name = "ceruleus"
version = "0.1.0"
edition = "2024"

[dependencies]
daemonize = "0.5.0"
dbus = "0.9.9"
futures = "0.3.31"
tokio = { version = "1.47.1", features = ["full"] }
log = "0.4.28"
env_logger = "0.11.8"
bluez-async = "0.8.2"
time = "0.3.43"
pretty_env_logger = "0.5.0"
