[package]
name = "ceruleus"
version = "0.1.0"
edition = "2024"

[dependencies]
daemonize = "0.5.0"
dbus = "0.9.9"
futures = "0.3.31"
tokio = { version = "1.47.1", features = ["full"] }
log = "0.4.28"
