[package]
name = "ceruleus"
version = "0.1.0"
edition = "2024"

[dependencies]
bluest = "0.6.9"
btleplug = "0.11.8"
daemonize = "0.5.0"
dbus = "0.9.9"
env_logger = "0.11.8"
futures = "0.3.31"
tokio = { version = "1.47.1", features = ["full"] }
